<?xml version="1.0"?>
<package format="2">
  <name>base_enhanced_teleop</name>
  <version>1.0.0</version>
  <description>
    Provides teleoperation to control robot base using keyboard. Based on turtlebot3_teleop package from Robotis.
  </description>
  <license>BSD</license>
  <author>Rodolphe Matias de Sousa</author>
  <author email="rodolphe.matias@icloud.com">Rodolphe Matias de Sousa</author>
  <maintainer email="rodolphe.matias@icloud.com">Rodolphe Matias de Sousa</maintainer>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>rospy</depend>
  <depend>geometry_msgs</depend>
</package>
