<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://relaxng.org/ns/structure/1.0"?>
<package format="3">
  <name>emergency_shutdown</name>
  <version>1.0.0</version>
  <description>
    The emergency_shutdown package provides the functions to
    shutdown ROS and the robot when an emergency is detected
    (low battery...)
  </description>
  <maintainer email="rodolphe.matias@icloud.com">Rodolphe Matias de Sousa</maintainer>
  <author>Rodolphe Matias de Sousa</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
