<?xml version="1.0"?>
<package>
  <name>nxt1_ros</name>
  <version>5.1.0</version>
  <description>
    The nxt1_ros package provides the bindings between the NXT world
    and the ROS world on the robot.  This package will create a ROS topic
    for each NXT1 sensor, and publish the sensor's data on this topic. The
    package also creates a topic for each NXT1 motor, which allows you
    to command the motor from ROS. The nxt1_ros bindings talk directly
    to the NXT1 brick over USB.
  </description>

  <maintainer email="rodolphe.matias@icloud.com">Rodolphe Matias de Sousa</maintainer>
  <author>Rodolphe Matias de Sousa</author>

  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>orocos_kdl</build_depend>
  <build_depend>nxt_msgs</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>sensor_msgs</build_depend>

  <run_depend>orocos_kdl</run_depend>
  <run_depend>nxt_msgs</run_depend>
  <run_depend>nxt_python</run_depend>
  <run_depend>rospy</run_depend>
  <run_depend>sensor_msgs</run_depend>
</package>
